version: '3.8'

services:
  # ZQAL SDK with Real-Time Orchestrator
  zqal-sdk:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zqal-sdk
    container_name: zion-zqal-sdk
    ports:
      - "8080:8080"    # WebSocket
      - "8081:8081"    # Socket.IO
      - "3000:3000"    # Web monitor (if served)
    volumes:
      - ../zqal-sdk:/app/zqal-sdk
      - ../examples:/app/examples
      - zqal-data:/app/data
    environment:
      - PYTHONPATH=/app
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import zion_realtime_orchestrator; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zion-network

  # ZION Node
  zion-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zion-node
    container_name: zion-node
    ports:
      - "18089:18089"  # RPC port
      - "18090:18090"  # P2P port
    volumes:
      - zion-blockchain:/app/blockchain
      - zion-data:/app/data
      - zion-logs:/app/logs
    environment:
      - ZION_RPC_TOKEN=${ZION_RPC_TOKEN:-default_token}
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - zqal-sdk
    networks:
      - zion-network

  # Mining Pool
  mining-pool:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mining-pool
    container_name: zion-mining-pool
    ports:
      - "3333:3333"    # Stratum port
      - "3334:3334"    # API port
      - "3336:3336"    # Cosmic Harmony port
    volumes:
      - pool-data:/app/data
      - pool-logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - POOL_HOST=0.0.0.0
      - ZION_NODE_RPC=http://zion-node:18089
    restart: unless-stopped
    depends_on:
      - zion-node
      - zqal-sdk
    networks:
      - zion-network

  # Rainbow Bridge
  rainbow-bridge:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rainbow-bridge
    container_name: zion-rainbow-bridge
    ports:
      - "9735:9735"    # Lightning mainnet
      - "9736:9736"    # Lightning testnet
    volumes:
      - bridge-data:/app/data
      - bridge-logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - zion-node
    networks:
      - zion-network

  # Web Monitor (Nginx for static files)
  web-monitor:
    image: nginx:alpine
    container_name: zion-web-monitor
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../zion_websocket_monitor.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - zqal-sdk
    networks:
      - zion-network

volumes:
  zqal-data:
    driver: local
  zion-blockchain:
    driver: local
  zion-data:
    driver: local
  zion-logs:
    driver: local
  pool-data:
    driver: local
  pool-logs:
    driver: local
  bridge-data:
    driver: local
  bridge-logs:
    driver: local

networks:
  zion-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16