global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Self-scrape Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Placeholder for future ZION metrics exporters
  # - job_name: 'zion-node'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['zion-node:9100']
