#!/bin/bash
################################################################################
# SSH Key Setup Instructions for Hetzner 91.98.122.165
# Date: 2025-10-24
# Purpose: Add SSH public key to authorized_keys for passwordless access
################################################################################

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  SSH Key Setup for root@91.98.122.165                        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"

# 1. Get the public key
SSH_PUBLIC_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDbGObSSmzSgT3rQ5VmpYCzf1EOmjqZXVyG86IuvGUql zion@91.98.122.165"

echo ""
echo "📝 Public Key (to add to server):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$SSH_PUBLIC_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "🎯 INSTRUCTIONS:"
echo ""
echo "OPTION A: Via Hetzner Cloud Console (Recommended)"
echo "───────────────────────────────────────────────────"
echo "1. Go to: https://console.hetzner.cloud"
echo "2. Click on your server: 91.98.122.165"
echo "3. Click 'Console' or 'VNC Console'"
echo "4. Login with root credentials"
echo "5. Run these commands:"
echo ""
echo "   mkdir -p ~/.ssh"
echo "   cat >> ~/.ssh/authorized_keys << 'EOF'"
echo "   $SSH_PUBLIC_KEY"
echo "   EOF"
echo "   chmod 700 ~/.ssh"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "6. Exit console"
echo "7. Then test: ssh hetzner"
echo ""
echo ""
echo "OPTION B: If you have password SSH access"
echo "───────────────────────────────────────────"
echo "Run this command (will prompt for root password):"
echo ""
echo "   ssh-copy-id -i ~/.ssh/id_ed25519_hetzner.pub root@91.98.122.165"
echo ""
echo "Then test: ssh hetzner"
echo ""
echo ""
echo "✅ After Setup - Test Connection:"
echo "──────────────────────────────────"
echo "$ ssh hetzner"
echo "# Should login without password"
echo ""
echo "$ ssh hetzner 'echo OK && uptime'"
echo "# Should show server status"
echo ""

echo ""
echo "🚀 Deployment Commands (after SSH key is added):"
echo "─────────────────────────────────────────────────"
echo ""
echo "1. Test connection:"
echo "   ssh hetzner 'uname -a'"
echo ""
echo "2. Copy deployment script:"
echo "   scp deployment/deploy_ssh_282_docker.sh hetzner:/tmp/"
echo ""
echo "3. Run deployment:"
echo "   ssh hetzner 'bash /tmp/deploy_ssh_282_docker.sh'"
echo ""
echo "4. Check status:"
echo "   ssh hetzner 'docker ps'"
echo ""
