# ZQAL Stdlib - Light Language Tones (minimal seed)
# Extend to 1..70 gradually; names are placeholders aligned to 7 Rays

[tones]
1  = "Initiation_Will_Blue"
2  = "Illumination_Wisdom_Yellow"
3  = "Compassion_Love_Pink"
4  = "Purity_Ascension_White"
5  = "Truth_Healing_Green"
6  = "Peace_Service_RubyGold"
7  = "Transmutation_Violet"
8  = "Power_of_Faith"
9  = "Clarity_of_Mind"
10 = "Grace_of_Heart"
11 = "Crystal_Gate"
12 = "Solar_Union"
13 = "Sirius_Alignment"
14 = "Metatron_Cube"
15 = "Merkaba_Spin"
16 = "Golden_Ratio_Phi"
17 = "Flower_of_Life_Pattern"
18 = "Tree_of_Life_Path"
19 = "Seraphic_Fire"
20 = "Cherubic_Wisdom"
21 = "Thrones_Justice"
22 = "Dominions_Sovereignty"
23 = "Powers_Protection"
24 = "Virtues_Miracles"
25 = "Principalities_Guardians"
26 = "Archangelic_Shield"
27 = "Angelus_Service"
28 = "Harmonic_432Hz"
29 = "DNA_Activation_12Strands"
30 = "Kundalini_Rise"
31 = "Lotus_Blossom"
32 = "Alpha_Omega"
33 = "Christ_Consciousness"
34 = "Bodhisattva_Vow"
35 = "Mahatma_Stream"
36 = "Vajra_Clarity"
37 = "Shakti_Power"
38 = "Shiva_Stillness"
39 = "Lakshmi_Abundance"
40 = "Hanuman_Devotion"
41 = "Rama_Dharma"
42 = "Sita_Purity"
43 = "Ganesha_ClearPath"
44 = "Rainbow_Bridge_44:44"
45 = "Avalokiteshvara_Compassion"
46 = "Green_Tara_Protection"
47 = "White_Tara_LongLife"
48 = "Manjushri_Wisdom"
49 = "Violet_Flame_Transmute"
50 = "Ruby_Gold_Service"
51 = "Emerald_Truth_Healing"
52 = "Sapphire_Faith"
53 = "Topaz_Illumination"
54 = "Amethyst_Purity"
55 = "Diamond_Integrity"
56 = "Opal_Inspiration"
57 = "Pearl_Peace"
58 = "Onyx_Protection"
59 = "Quartz_Amplification"
60 = "Lapis_Communication"
61 = "Solar_Logoi_Helios_Vesta"
62 = "Sirius_Surya"
63 = "Sanat_Kumara_Flame"
64 = "Metatron_Command"
65 = "Melchizedek_Order"
66 = "Elohim_Builders"
67 = "Shekinah_Presence"
68 = "Holy_Spirit_Ruah"
69 = "Source_I_AM"
70 = "Central_Sun_Radiance_JAY_RAM_SITA_HANUMAN"